# Generated by Django 2.2.3 on 2019-07-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
